// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package dish

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DishServiceClient is the client API for DishService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DishServiceClient interface {
	AddDish(ctx context.Context, in *AddDishReq, opts ...grpc.CallOption) (*Empty, error)
	AllDishes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DishesResp, error)
}

type dishServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDishServiceClient(cc grpc.ClientConnInterface) DishServiceClient {
	return &dishServiceClient{cc}
}

func (c *dishServiceClient) AddDish(ctx context.Context, in *AddDishReq, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/dish.DishService/AddDish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dishServiceClient) AllDishes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DishesResp, error) {
	out := new(DishesResp)
	err := c.cc.Invoke(ctx, "/dish.DishService/AllDishes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DishServiceServer is the server API for DishService service.
// All implementations must embed UnimplementedDishServiceServer
// for forward compatibility
type DishServiceServer interface {
	AddDish(context.Context, *AddDishReq) (*Empty, error)
	AllDishes(context.Context, *Empty) (*DishesResp, error)
	mustEmbedUnimplementedDishServiceServer()
}

// UnimplementedDishServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDishServiceServer struct {
}

func (UnimplementedDishServiceServer) AddDish(context.Context, *AddDishReq) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDish not implemented")
}
func (UnimplementedDishServiceServer) AllDishes(context.Context, *Empty) (*DishesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllDishes not implemented")
}
func (UnimplementedDishServiceServer) mustEmbedUnimplementedDishServiceServer() {}

// UnsafeDishServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DishServiceServer will
// result in compilation errors.
type UnsafeDishServiceServer interface {
	mustEmbedUnimplementedDishServiceServer()
}

func RegisterDishServiceServer(s grpc.ServiceRegistrar, srv DishServiceServer) {
	s.RegisterService(&DishService_ServiceDesc, srv)
}

func _DishService_AddDish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDishReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DishServiceServer).AddDish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dish.DishService/AddDish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DishServiceServer).AddDish(ctx, req.(*AddDishReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DishService_AllDishes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DishServiceServer).AllDishes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dish.DishService/AllDishes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DishServiceServer).AllDishes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// DishService_ServiceDesc is the grpc.ServiceDesc for DishService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DishService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dish.DishService",
	HandlerType: (*DishServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddDish",
			Handler:    _DishService_AddDish_Handler,
		},
		{
			MethodName: "AllDishes",
			Handler:    _DishService_AllDishes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dish/dish.proto",
}
