// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: dish/dish.proto

package dish

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//entity
type Dish struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string  `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price       float32 `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *Dish) Reset() {
	*x = Dish{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dish_dish_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dish) ProtoMessage() {}

func (x *Dish) ProtoReflect() protoreflect.Message {
	mi := &file_dish_dish_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dish.ProtoReflect.Descriptor instead.
func (*Dish) Descriptor() ([]byte, []int) {
	return file_dish_dish_proto_rawDescGZIP(), []int{0}
}

func (x *Dish) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Dish) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dish) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Dish) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

//req
type AddDishReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dish *Dish `protobuf:"bytes,1,opt,name=dish,proto3" json:"dish,omitempty"`
}

func (x *AddDishReq) Reset() {
	*x = AddDishReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dish_dish_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddDishReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDishReq) ProtoMessage() {}

func (x *AddDishReq) ProtoReflect() protoreflect.Message {
	mi := &file_dish_dish_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDishReq.ProtoReflect.Descriptor instead.
func (*AddDishReq) Descriptor() ([]byte, []int) {
	return file_dish_dish_proto_rawDescGZIP(), []int{1}
}

func (x *AddDishReq) GetDish() *Dish {
	if x != nil {
		return x.Dish
	}
	return nil
}

type DishesResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dishes []*Dish `protobuf:"bytes,1,rep,name=dishes,proto3" json:"dishes,omitempty"`
}

func (x *DishesResp) Reset() {
	*x = DishesResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dish_dish_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DishesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DishesResp) ProtoMessage() {}

func (x *DishesResp) ProtoReflect() protoreflect.Message {
	mi := &file_dish_dish_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DishesResp.ProtoReflect.Descriptor instead.
func (*DishesResp) Descriptor() ([]byte, []int) {
	return file_dish_dish_proto_rawDescGZIP(), []int{2}
}

func (x *DishesResp) GetDishes() []*Dish {
	if x != nil {
		return x.Dishes
	}
	return nil
}

//base
type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dish_dish_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_dish_dish_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_dish_dish_proto_rawDescGZIP(), []int{3}
}

var File_dish_dish_proto protoreflect.FileDescriptor

var file_dish_dish_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x64, 0x69, 0x73, 0x68, 0x2f, 0x64, 0x69, 0x73, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x64, 0x69, 0x73, 0x68, 0x22, 0x62, 0x0a, 0x04, 0x44, 0x69, 0x73, 0x68, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x2c, 0x0a, 0x0a, 0x41,
	0x64, 0x64, 0x44, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x04, 0x64, 0x69, 0x73,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x64, 0x69, 0x73, 0x68, 0x2e, 0x44,
	0x69, 0x73, 0x68, 0x52, 0x04, 0x64, 0x69, 0x73, 0x68, 0x22, 0x30, 0x0a, 0x0a, 0x44, 0x69, 0x73,
	0x68, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x06, 0x64, 0x69, 0x73, 0x68, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x64, 0x69, 0x73, 0x68, 0x2e, 0x44,
	0x69, 0x73, 0x68, 0x52, 0x06, 0x64, 0x69, 0x73, 0x68, 0x65, 0x73, 0x22, 0x07, 0x0a, 0x05, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x32, 0x63, 0x0a, 0x0b, 0x44, 0x69, 0x73, 0x68, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x44, 0x69, 0x73, 0x68, 0x12, 0x10,
	0x2e, 0x64, 0x69, 0x73, 0x68, 0x2e, 0x41, 0x64, 0x64, 0x44, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71,
	0x1a, 0x0b, 0x2e, 0x64, 0x69, 0x73, 0x68, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x2a, 0x0a,
	0x09, 0x41, 0x6c, 0x6c, 0x44, 0x69, 0x73, 0x68, 0x65, 0x73, 0x12, 0x0b, 0x2e, 0x64, 0x69, 0x73,
	0x68, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x10, 0x2e, 0x64, 0x69, 0x73, 0x68, 0x2e, 0x44,
	0x69, 0x73, 0x68, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x64,
	0x69, 0x73, 0x68, 0x3b, 0x64, 0x69, 0x73, 0x68, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dish_dish_proto_rawDescOnce sync.Once
	file_dish_dish_proto_rawDescData = file_dish_dish_proto_rawDesc
)

func file_dish_dish_proto_rawDescGZIP() []byte {
	file_dish_dish_proto_rawDescOnce.Do(func() {
		file_dish_dish_proto_rawDescData = protoimpl.X.CompressGZIP(file_dish_dish_proto_rawDescData)
	})
	return file_dish_dish_proto_rawDescData
}

var file_dish_dish_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_dish_dish_proto_goTypes = []interface{}{
	(*Dish)(nil),       // 0: dish.Dish
	(*AddDishReq)(nil), // 1: dish.AddDishReq
	(*DishesResp)(nil), // 2: dish.DishesResp
	(*Empty)(nil),      // 3: dish.Empty
}
var file_dish_dish_proto_depIdxs = []int32{
	0, // 0: dish.AddDishReq.dish:type_name -> dish.Dish
	0, // 1: dish.DishesResp.dishes:type_name -> dish.Dish
	1, // 2: dish.DishService.AddDish:input_type -> dish.AddDishReq
	3, // 3: dish.DishService.AllDishes:input_type -> dish.Empty
	3, // 4: dish.DishService.AddDish:output_type -> dish.Empty
	2, // 5: dish.DishService.AllDishes:output_type -> dish.DishesResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dish_dish_proto_init() }
func file_dish_dish_proto_init() {
	if File_dish_dish_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dish_dish_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dish); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dish_dish_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddDishReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dish_dish_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DishesResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dish_dish_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dish_dish_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dish_dish_proto_goTypes,
		DependencyIndexes: file_dish_dish_proto_depIdxs,
		MessageInfos:      file_dish_dish_proto_msgTypes,
	}.Build()
	File_dish_dish_proto = out.File
	file_dish_dish_proto_rawDesc = nil
	file_dish_dish_proto_goTypes = nil
	file_dish_dish_proto_depIdxs = nil
}
